# Generated by Django 4.1.6 on 2023-02-18 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodgram', '0003_alter_recipes_author_alter_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='in_shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='В листе покупок у'),
        ),
    ]
