# Generated by Django 4.1.6 on 2023-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0004_alter_recipes_favorited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2023-02-18 19:10:53.036696', verbose_name='Даnа публикации'),
            preserve_default=False,
        ),
    ]
