# Generated by Django 4.1.6 on 2023-02-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role_alter_user_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'пользователь')], default='user', max_length=13, verbose_name='Роль пользователя'),
        ),
    ]
